version: '3'
services:
  api:
    build: ./api
    container_name: api
    networks:
      - red_tareas

  cliente:
    build: ./cliente
    container_name: cliente
    depends_on:
      - api
    networks:
      - red_tareas

networks:
  red_tareas:
    driver: bridge
